version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - consul
      - jaeger
    # networks:
    #   - network
    environment:
      - DB=consul
      - DBPORT=8500
      JAEGER_ADDRESS: ${JAEGER_ADDRESS}

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - consul-data:/consul/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

    jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    # networks:
    #   - network

volumes:
  consul-data:
  prometheus-data: